src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Family 1</fullName>
                </value>
                <value>
                    <fullName>Family 2</fullName>
                </value>
                <value>
                    <fullName>Family 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type_1</fullName>
                    <label>Type 1</label>
                </value>
                <value>
                    <fullName>Type_2</fullName>
                    <label>Type 2</label>
                </value>
                <value>
                    <fullName>Type_3</fullName>
                    <label>Type 3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderItemTriggerTest.cls
@IsTest
private class OrderItemTriggerTest {
    @testSetup
	public static void createOrder() {
		Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'tests', Email='testesestr@testtesteets.com', 
            EmailEncodingKey='UTF-8', LastName='Testingtest', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, isManager__c = true, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testesestr@testtesteets.com');
		insert u;

		List<Account> accounts = new List<Account>{
			new Account(
				Name = 'Account to test 123',
				AccountNumber = '123456',
				OwnerId = UserInfo.getUserId()
			)};
		insert accounts;

		List<Product__c> products = new List<Product__c> {
			new Product__c(
				Name = 'Product 1 test',
            	Type__c = 'Type_2',
				Family__c = 'Family 1',
                Price__c = 200
			),
			new Product__c(
				Name = 'Product 2 test',
            	Type__c = 'Type_3',
				Family__c = 'Family 2',
                Price__c = 1000
			),
            new Product__c(
				Name = 'Product 3 test',
				Type__c = 'Type_1',
            	Family__c = 'Family 3',
                Price__c = 2000
			)};
		insert products;

		List<Order__c> orders = new List<Order__c>{
			new Order__c(
				Name = 'Order to test',
				AccountId__c = accounts[0].Id,
				TotalPrice__c = 0,
                TotalProductCount__c = 0
			)};
		insert orders;

		List<OrderItem__c> orderItems = new List<OrderItem__c>{
			new OrderItem__c(
				Name = 'Item to test 123',
				ProductId__c = products[0].Id,
				OrderId__c = orders[0].Id,
				Quantity__c = 3
			),
			new OrderItem__c(
				Name = 'Item to test 321',
				ProductId__c = products[1].Id,
				OrderId__c = orders[0].Id,
				Quantity__c = 2
			),
            new OrderItem__c(
				Name = 'Item to test 567',
				ProductId__c = products[2].Id,
				OrderId__c = orders[0].Id,
				Quantity__c = 10
			)};
		insert orderItems;
	}

	@isTest
	static void testOrderTrigger() {
		Order__c Order = [SELECT TotalPrice__c, TotalProductCount__c from Order__c limit 1];
		System.assertEquals(22600, Order.TotalPrice__c);
		System.assertEquals(15, Order.TotalProductCount__c);
	}
}