src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Family 1</fullName>
                </value>
                <value>
                    <fullName>Family 2</fullName>
                </value>
                <value>
                    <fullName>Family 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type_1</fullName>
                    <label>Type 1</label>
                </value>
                <value>
                    <fullName>Type_2</fullName>
                    <label>Type 2</label>
                </value>
                <value>
                    <fullName>Type_3</fullName>
                    <label>Type 3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cartControllerTest.cls
@IsTest
public class cartControllerTest {
	@testSetup
	static void createProducts() {
		List<Product__c> products = new List<Product__c>();
		products.add(new Product__c(
			Name = 'Product 1 test',
            Type__c = 'Type_2',
			Family__c = 'Family 1'
			)
		);
		products.add(new Product__c(
			Name = 'Product 2 test',
            Type__c = 'Type_3',
			Family__c = 'Family 2'
			)
		);
		insert products;
	}
	
	@isTest
	static void testCartProducts() {
		List<Id> testProducts = new List<Id>();
		List<Product__c> products = [SELECT Id from Product__c];
		testProducts.add(products[0].Id);
		testProducts.add(products[1].Id);
		testProducts.add(products[1].Id);
		String result = cartController.cartProducts(testProducts);
		System.assertEquals('{"' + products[1].Id + '":2,"' + products[0].Id + '":1}', result);
	}
}